//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adult
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public byte GenderId { get; set; }
        public short EducationLevelId { get; set; }
        public System.Guid BeneficiaryId { get; set; }
        public byte AdultRelationshipId { get; set; }
        public bool Disability { get; set; }
        public string Disabilities { get; set; }
        public Nullable<byte> BirthDay { get; set; }
        public Nullable<byte> BirthMonth { get; set; }
        public short BirthYear { get; set; }
        public Nullable<byte> Status { get; set; }
        public bool EmplSameCompany { get; set; }
        public byte PrimaryOccupationId { get; set; }
        public byte SecondaryOccupationId { get; set; }
        public Nullable<byte> PrimaryWorkDaysM { get; set; }
        public Nullable<byte> SecondaryWorkDaysM { get; set; }
        public Nullable<short> PrimaryDailyWage { get; set; }
        public Nullable<short> SecondaryDailyWage { get; set; }
        public Nullable<System.DateTime> OrigEntryDate { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual Beneficiary Beneficiary { get; set; }
        public virtual AdultRelationship AdultRelationship { get; set; }
        public virtual Occupation PrimaryOccupation { get; set; }
        public virtual Occupation SecondaryOccupation { get; set; }
    }
}
