//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public Child()
        {
            this.MonthlyEduExpenses = 0D;
        }
    
        public System.Guid Id { get; set; }
        public System.Guid BeneficiaryId { get; set; }
        public string Name { get; set; }
        public byte GenderId { get; set; }
        public byte ChildRelationshipId { get; set; }
        public bool Disability { get; set; }
        public string Disabilities { get; set; }
        public bool EnrolledInSchool { get; set; }
        public string WhyNotInSchool { get; set; }
        public Nullable<byte> SchoolTypeId { get; set; }
        public Nullable<byte> SchoolDistanceId { get; set; }
        public Nullable<byte> ClassLevelId { get; set; }
        public Nullable<double> MonthlyEduExpenses { get; set; }
        public Nullable<byte> BirthDay { get; set; }
        public Nullable<byte> BirthMonth { get; set; }
        public short BirthYear { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> SchoolAttendance { get; set; }
        public Nullable<System.DateTime> OrigEntryDate { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Beneficiary Beneficiary { get; set; }
        public virtual SchoolType SchoolType { get; set; }
        public virtual ClassLevel ClassLevel { get; set; }
        public virtual ChildRelationship ChildRelationship { get; set; }
        public virtual SchoolDistance SchoolDistance { get; set; }
        public virtual SchoolDayPerWeek SchoolDayPerWeek { get; set; }
    }
}
