//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PartnerCompany> PartnerCompanies { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Beneficiary> Beneficiaries { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Caste> Castes { get; set; }
        public virtual DbSet<Disability> Disabilities { get; set; }
        public virtual DbSet<EducationLevel> EducationLevels { get; set; }
        public virtual DbSet<Adult> Adults { get; set; }
        public virtual DbSet<AdultRelationship> AdultRelationships { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<ChildRelationship> ChildRelationships { get; set; }
        public virtual DbSet<SchoolType> SchoolTypes { get; set; }
        public virtual DbSet<ClassLevel> ClassLevels { get; set; }
        public virtual DbSet<PartnerStaffMember> PartnerStaffMembers { get; set; }
        public virtual DbSet<StaffType> StaffTypes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<PartnerAdmin> PartnerAdmins { get; set; }
        public virtual DbSet<AssetType> AssetTypes { get; set; }
        public virtual DbSet<HouseholdAsset> HouseholdAssets { get; set; }
        public virtual DbSet<Meals> Meals { get; set; }
        public virtual DbSet<MealType> MealTypes { get; set; }
        public virtual DbSet<FoodSourceType> FoodSourceTypes { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<HAssetValue> HAssetValues { get; set; }
        public virtual DbSet<SchoolDistance> SchoolDistances { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<SchoolDayPerWeek> SchoolDaysPerWeek { get; set; }
        public virtual DbSet<MajorExpensesInfo> MajorExpenses { get; set; }
        public virtual DbSet<HealthCareInfo> HealthCareInfos { get; set; }
        public virtual DbSet<HcProviderType> HcProviderTypes { get; set; }
        public virtual DbSet<HealthIssueType> HealthIssueTypes { get; set; }
        public virtual DbSet<MedSourceType> MedSourceTypes { get; set; }
        public virtual DbSet<GovernmentServicesInfo> GovernmentServices { get; set; }
        public virtual DbSet<GovCardType> GovCardTypes { get; set; }
        public virtual DbSet<GovServiceType> GovServiceTypes { get; set; }
        public virtual DbSet<HousingInfo> HousingInfoes { get; set; }
        public virtual DbSet<NumberOfRoomsType> NumberOfRoomsTypes { get; set; }
        public virtual DbSet<RoofMaterialType> RoofMaterialTypes { get; set; }
        public virtual DbSet<WallMaterialType> WallMaterialTypes { get; set; }
        public virtual DbSet<WaterSourceType> WaterSourceTypes { get; set; }
        public virtual DbSet<ToiletType> ToiletTypes { get; set; }
        public virtual DbSet<CookingEnergyType> CookingEnergyTypes { get; set; }
        public virtual DbSet<HouseQualityType> HouseQualityTypes { get; set; }
        public virtual DbSet<WaterSourceDistanceType> WaterSourceDistanceTypes { get; set; }
        public virtual DbSet<HouseOwnershipType> HouseOwnershipTypes { get; set; }
        public virtual DbSet<SavingsType> SavingsTypes { get; set; }
        public virtual DbSet<LoanPurposeType> LoanPurposeTypes { get; set; }
        public virtual DbSet<GrainType> GrainTypes { get; set; }
        public virtual DbSet<PulseType> PulseTypes { get; set; }
        public virtual DbSet<VegetableType> VegetableTypes { get; set; }
        public virtual DbSet<PKG_M_Type> PKG_M_Type { get; set; }
        public virtual DbSet<HistoryRec> HistoryRecs { get; set; }
        public virtual DbSet<AvgNonVegPerMType> AvgNonVegPerMTypes { get; set; }
        public virtual DbSet<PKGPerMType> PKGPerMTypes { get; set; }
        public virtual DbSet<WhyNotInSchoolType> WhyNotInSchoolTypes { get; set; }
    }
}
