//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Towns = new HashSet<Town>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
        public string Abbr { get; set; }
        public short StateId { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Town> Towns { get; set; }
    }
}
