//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAssetValue
    {
        public int Id { get; set; }
        public System.Guid PartnerCompanyId { get; set; }
        public short AssetTypeId { get; set; }
        public int Value { get; set; }
        public Nullable<System.DateTime> OrigEntryDate { get; set; }
    
        public virtual AssetType AssetType { get; set; }
    }
}
