//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCareInfo
    {
        public System.Guid Id { get; set; }
        public string HcProviders { get; set; }
        public Nullable<short> HcFrequencyQ { get; set; }
        public string HealthIssues { get; set; }
        public Nullable<int> TreatmentCostsQ { get; set; }
        public string MedSources { get; set; }
        public Nullable<System.DateTime> OrigEntryDate { get; set; }
    
        public virtual Beneficiary Beneficiary { get; set; }
    }
}
