//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryRec
    {
        public int Id { get; set; }
        public System.Guid RefId { get; set; }
        public byte Type { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid User { get; set; }
        public string Value { get; set; }
        public bool Created { get; set; }
    }
}
