//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseholdAsset
    {
        public long Id { get; set; }
        public short AssetTypeId { get; set; }
        public System.Guid BeneficiaryId { get; set; }
        public short Count { get; set; }
        public Nullable<int> TotalValue { get; set; }
        public Nullable<System.DateTime> OrigEntryDate { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual Beneficiary Beneficiary { get; set; }
    }
}
