//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerAdmin
    {
        public System.Guid Id { get; set; }
        public System.Guid PartnerCompanyId { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual PartnerCompany PartnerCompany { get; set; }
    }
}
