//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerStaffMember
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public byte GenderId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public Nullable<byte> BirthDay { get; set; }
        public Nullable<byte> BirthMonth { get; set; }
        public short BirthYear { get; set; }
        public byte StaffTypeId { get; set; }
        public string InternalPartnerEmployeeId { get; set; }
        public System.Guid PartnerCompanyId { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual StaffType StaffType { get; set; }
        public virtual PartnerCompany PartnerCompany { get; set; }
    }
}
