//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpayaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CountryId { get; set; }
        public short StateId { get; set; }
        public short DistrictId { get; set; }
        public string PostalCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual District District { get; set; }
    }
}
